name = "waymint"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CACHE"
id = "e09e5989d46b48fb9f4cd8ecd423ff74"
preview_id = "placeholder_preview_id"
